services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=haldersaas
      - POSTGRES_PASSWORD=723235rafael
      - POSTGRES_DB=whatsai
